lovebegin: 2023-01-01

banner: https://api.toshiki.dev/random.php

# å·¦è¾¹å¤´åƒçš„åç§°
leftname: å®‰ç”°ä¿Šæ¨¹
leftavatar: https://q1.qlogo.cn/g?b=qq&nk=1959796501&s=640

# å³è¾¹å¤´åƒçš„åç§°
rightname: ææ€ä½³
rightavatar: https://q1.qlogo.cn/g?b=qq&nk=2846931395&s=640


slogan: ğŸ’•æ„¿ä½ ä¸‰å†¬æš–ï¼Œæ„¿ä½ å¤©ä¸å¯’ğŸ‚

# ç«™ç‚¹åç§°
sitename: ğŸ’–é‚£å¹´åˆå¤ğŸ’–

waline: https://love.comment.toshiki.dev/

theme: koi

lovelist:
  - desc: ä¸€èµ·çœ‹æ—¥å‡ºğŸŒ…
    status: 0
    img:
  - desc: ä¸€èµ·çœ‹æ—¥è½ğŸŒ„
    status: 0
    img:
  - desc: ä¸€èµ·çœ‹ç»šçƒ‚çš„çƒŸèŠ±ğŸŒŸ
    status: 0
    img:
  - desc: ä¸€èµ·åƒè·¯è¾¹æ‘ŠğŸ–
    status: 0
    img:
  - desc: ä¸€èµ·å”±é¦–æ­Œå¹¶å½•ä¸‹æ¥ğŸ¤
    status: 0
    img:
  - desc: ä¸€èµ·ç©¿æƒ…ä¾£è£…é€›è¡—ğŸ‘«
    status: 0
    img:
  - desc: ä¸€èµ·å»æ¸¸ä¹å›­ï¼ˆè¿ªå£«å°¼ï¼‰å—¨ä¸€å¤©ğŸˆ
    status: 0
    img:
  - desc: é™ªå¯¹æ–¹è¿‡ç”Ÿæ—¥ğŸ‚
    status: 0
    img:
  - desc: ä¸€èµ·å»æµ·å—çš„å¤©æ¶¯æµ·è§’ğŸŒ´
    status: 0
    img:
  - desc: ä¸€èµ·å»ä½ çš„å°å­¦ã€åˆä¸­ã€é«˜ä¸­ã€å¤§å­¦ğŸ‘«
    status: 0
    img:
  - desc: ä¸€èµ·å»æˆ‘çš„å°å­¦ã€åˆä¸­ã€é«˜ä¸­ã€å¤§å­¦ğŸ‘«
    status: 0
    img:
  - desc: ä¸€èµ·æ”¾å­”æ˜ç¯ğŸ®
    status: 0
    img:
  - desc: å»éä¸­å›½çš„æ¯ä¸€ä¸ªçœä»½ğŸš‰
    status: 0
    img:
  - desc: ä¸€èµ·å»é’“é±¼ğŸŸ
    status: 0
    img:
  - desc: ä¸€èµ·å»å½“å¿—æ„¿è€…ã€ä¹‰å·¥ğŸ‘®
    status: 0
    img:
  - desc: ä¸€èµ·åä¸€è¾†æ²¡åè¿‡çš„è½¦ï¼Œåœ¨é™Œç”Ÿçš„åœ°æ–¹ä¸‹è½¦é€›ğŸšƒ
    status: 0
    img:
  - desc: æ·‹ä¸€æ¬¡é›¨ï¼Œåœ¨é›¨ä¸­æ¼«æ­¥â˜”
    status: 0
    img:
  - desc: ä¸ºå¯¹æ–¹åšæ—©é¤ğŸ”
    status: 0
    img:
  - desc: åœ¨æ²™æ»©ä¸Šå†™ä¸‹å½¼æ­¤çš„åå­—âœ
    status: 0
    img:
  - desc: ä¸€èµ·çœ‹åˆé›ªâ›„
    status: 0
    img:
  - desc: ç©¿å½¼æ­¤çš„è¡£æœğŸ‘¯
    status: 0
    img:
  - desc: ä¸€èµ·å»åè¿‡å±±è½¦ğŸ
    status: 0
    img:
  - desc: å˜´å¯¹å˜´åƒä¸œè¥¿ğŸœ
    status: 0
    img:
  - desc: ä¸€èµ·å»æ¸¸æ³³ğŸŠ
    status: 0
    img:
  - desc: å»éäººæ°‘å¸èƒŒåçš„é£æ™¯â›³
    status: 0
    img:
  - desc: ä¸¤ä¸ªäººä¸€èµ·é”»ç‚¼è¿åŠ¨ğŸƒğŸ’ƒ
    status: 0
    img:
  - desc: ä¸€èµ·çˆ¬å±±ğŸ’‘
    status: 0
    img:
  - desc: åœ¨è€³è¾¹ä½å£°æ—–æ—"æˆ‘çˆ±ä½ "ğŸ’–
    status: 0
    img:
  - desc: ä¸€èµ·å¯¹ç€æµæ˜Ÿè®¸æ„¿ğŸŒ 
    status: 0
    img:
  - desc: ä¸€èµ·æ‰‹æ‹‰æ‰‹å‹é©¬è·¯ğŸ‘«
    status: 0
    img:
  - desc: ä¸€èµ·ååœ¨é˜³å°ï¼Œæ™’ç€å¤ªé˜³ï¼Œç£•ç€ç“œå­ï¼ŒèŠç€å¤©ğŸ‘
    status: 0
    img:
  - desc: ä¸€èµ·å…»ä¸€åªå® ç‰©ğŸ¶
    status: 0
    img:
  - desc: åœ¨å…¬å…±åœºåˆä¸‹ä¸€èµ·å–å¨ƒå“ˆå“ˆğŸ¼
    status: 0
    img:
  - desc: ä¸€èµ·å»ä¹°èœã€åšé¥­ã€åˆ·ç¢—ğŸ›
    status: 0
    img:
  - desc: ä¸€èµ·å»åçƒ­æ°”çƒğŸˆ
    status: 0
    img:
  - desc: å¸¦æˆ‘å»ä½ ç«¥å¹´å±…ä½çš„åœ°æ–¹èµ°ä¸€èµ°ğŸ‘©
    status: 0
    img:
  - desc: å¸¦ä½ å»æˆ‘ç«¥å¹´å±…ä½çš„åœ°æ–¹èµ°ä¸€èµ°ğŸ§‘
    status: 0
    img:
  - desc: ä¸€èµ·å †é›ªäººâ›„
    status: 0
    img:
  - desc: ä¸€èµ·åæ‘©å¤©è½®ï¼Œåœ¨æœ€é«˜å¤„æ‹¥å»ğŸ’
    status: 0
    img:
  - desc: ä¸€èµ·ç”¨å‹ºå­åƒè¥¿ç“œğŸ‰
    status: 0
    img:
  - desc: ä¸€èµ·æ¡è´å£³ğŸš
    status: 0
    img:
  - desc: çœ‹ä¸€æ¬¡å†°ç¯â›²
    status: 0
    img:
  - desc: ä¸€èµ·å»çœ‹æµ·ğŸŒŠ
    status: 0
    img:
  - desc: ä¸€èµ·èµ°æ²™æ»©ğŸš¶
    status: 0
    img:
  - desc: ä¸€èµ·å»çœ‹æ”¯ä»˜å®å…±åŒç§ä¸‹çš„æ ‘ğŸ‹
    status: 0
    img:
  - desc: ä¸€èµ·è·¨å¹´ï¼Œé€šå®µå®ˆå²ğŸ“º
    status: 0
    img:
  - desc: é€å½¼æ­¤å‡ºé—¨ï¼Œç»™ä¸€ä¸ªå¤§å¤§çš„æ‹¥æŠ±ä¸å•µå•µğŸ˜š
    status: 0
    img:
  - desc: ä¸€èµ·çœ‹ä¹¦ï¼Œè£…æ»¡æˆ‘ä»¬çš„ä¹¦æ¶ğŸ’¡
    status: 0
    img:
  - desc: ä¸ºå¯¹æ–¹ç©¿è¡£æœã€ç³»é‹å¸¦ğŸ™…
    status: 0
    img:
  - desc: æ¨å¯¹æ–¹ç©ç§‹åƒğŸ’
    status: 0
    img:
  - desc: ä¸€èµ·å»å‚åŠ æœ‹å‹çš„å©šç¤¼ğŸ’•
    status: 0
    img:
  - desc: åœ¨é©¬å°”ä»£å¤«ï¼Œä½“éªŒç»ç’ƒåœ°æ¿çš„æµ·ä¸Šå°å±‹ğŸ¡
    status: 0
    img:
  - desc: ä¸€èµ·åä¸€æ¬¡é£æœºğŸ›«
    status: 0
    img:
  - desc: ä¸€èµ·åä¸€æ¬¡æ¸¸è½®ğŸš¤
    status: 0
    img:
  - desc: ä¸€èµ·å»çœ‹ä¸€æ¬¡æ¼”å”±ä¼šğŸµ
    status: 0
    img:
  - desc: ä¸€èµ·åœ¨æµ´ç¼¸é‡Œæ³¡æ¾¡ğŸ›€
    status: 0
    img:
  - desc: ä¸€èµ·å»çœ‹æµ·è±šğŸ¬
    status: 0
    img:
  - desc: ä¸€èµ·å»æ¡è½å¶ğŸ
    status: 0
    img:
  - desc: å¼€è½¦çº¢ç¯æ—¶å«ä½ å•µå•µğŸš—
    status: 0
    img:
  - desc: ä¸€èµ·å®Œæˆä¸€ä¸ªå†’é™©åˆºæ¿€çš„æŒ‘æˆ˜ğŸ’€
    status: 0
    img:
  - desc: ä¸€èµ·æ²¿ç€é“è½¨èµ°ğŸš‚
    status: 0
    img:
  - desc: ä¸€èµ·å»çœ‹åŸƒè²å°”é“å¡”ï¼Œåœ¨å¡”ä¸‹æ‹¥å»ğŸ‘„
    status: 0
    img:
  - desc: ä¸€èµ·è®¾è®¡æ•´ç†æˆ¿é—´ğŸ’
    status: 0
    img:
  - desc: å¾’æ­¥èµ°å®ŒåŒ—äº¬äºŒç¯ğŸ‘Ÿ
    status: 0
    img:
  - desc: ä¸å¥½æœ‹å‹ä¸€èµ·ï¼Œäº«å—å››äººçº¦ä¼šçš„ç¾å¦™ğŸ’œğŸ’›ğŸ’šğŸ’™
    status: 0
    img:
  - desc: ä¸ºä»–æ‰“é¢†å¸¦ğŸ”«
    status: 0
    img:
  - desc: æˆ‘å«ä½ ä¸€æ¬¡â€œè€å©†â€ï¼Œä½ å«æˆ‘ä¸€æ¬¡â€œè€å…¬â€ğŸ‘¨â€â¤ï¸â€ğŸ’‹â€ğŸ‘¨
    status: 0
    img:
  - desc: å¸¦ä½ åœ¨åˆå¤œå¼€è½¦å…œé£ğŸš™
    status: 0
    img:
  - desc: ä¸ºå¥¹æ¶‚æŒ‡ç”²æ²¹ğŸ’…
    status: 0
    img:
  - desc: æ¥ä¸€æ¬¡æµªæ¼«çš„å°æƒ…è¶£ğŸ˜
    status: 0
    img:
  - desc: åœ¨é˜³å°ä¸Šå…»ç€ä¸€æ’å¤šè‚‰æ¤ç‰©ğŸ¥¦
    status: 0
    img:
  - desc: ä¸€èµ·è¿‡ä¸€æ¬¡å…­ä¸€å„¿ç«¥èŠ‚ğŸ‘§ğŸ‘¦
    status: 0
    img:
  - desc: å…¥ä½ä¸€æ¬¡äº”æ˜Ÿçº§é…’åº—ğŸ¨
    status: 0
    img:
  - desc: ä¸ºå½¼æ­¤æ¢ä¸€ä¸ªå¯¹æ–¹å¿ƒä»ªçš„å‘å‹ï¼Œä¸è®ºé•¿çŸ­çƒ«æŸ“ğŸ’‡
    status: 0
    img:
  - desc: å·å·è§‚å¯Ÿå¯¹æ–¹ç†Ÿç¡çš„æ¨¡æ ·ï¼Œè®°å½•ä¸‹æ¥ğŸ“·
    status: 0
    img:
  - desc: ä¸€èµ·å»æ‰“ç”µç©ğŸ‘¾
    status: 0
    img:
  - desc: ä¸€èµ·ç»™å¯¹æ–¹å†™ä¿¡ï¼Œè¯»ç»™å¯¹æ–¹å¬ğŸ“„
    status: 0
    img:
  - desc: ä¸€èµ·æ»‘é›ªï¼Œæ‘”å€’ä¹Ÿè¦æ‹‰ç€ä½ ğŸ¿
    status: 0
    img:
  - desc: æ‹¥æœ‰æˆ‘ä»¬ç‹¬ç‰¹çš„æƒ…ä¾£æˆ’æŒ‡ğŸ’
    status: 0
    img:
  - desc: ä¸€èµ·å®Œæˆä¸€å‰¯åƒç‰‡æ‹¼å›¾ğŸ˜œ
    status: 0
    img:
  - desc: ä¸€èµ·å»å¤©å®‰é—¨çœ‹å‡æ——ä»ªå¼ğŸš„
    status: 0
    img:
  - desc: ä¸€èµ·åŒ…é¥ºå­ğŸ¥Ÿ
    status: 0
    img:
  - desc: ä¸€èµ·å»åƒè‡ªåŠ©é¤ï¼ŒæŠŠæ²¡å°è¿‡çš„é£Ÿæéƒ½å°è¯•ä¸€éğŸ”ª
    status: 0
    img:
  - desc: å»æ‹ä¸€å›å†™çœŸğŸ“¸
    status: 0
    img:
  - desc: ä¸€èµ·å»æ–°åŠ å¡çœ‹ç„°ç«è¡¨æ¼”ğŸ‡
    status: 0
    img:
  - desc: ä¸€èµ·å»çœ‹æå…‰âš¡âš¡
    status: 0
    img:
  - desc: èƒŒç€å¥¹èµ°ä¸€æ®µè·¯ğŸ‘£
    status: 0
    img:
  - desc: ä¸€èµ·èµæœˆğŸŒ™
    status: 0
    img:
  - desc: ä¸€èµ·å»çœ‹æ¨±èŠ±ğŸŒ¸
    status: 0
    img:
  - desc: ä»¥å–äº¤æ¯é…’çš„æ–¹å¼å–ä¸œè¥¿ğŸ¥‚
    status: 0
    img:
  - desc: ä¸€èµ·ä¹°ä¸€å¼ å½©ç¥¨ğŸ«
    status: 0
    img:
  - desc: åœ¨æ ‘ä¸‹åŸ‹ä¸‹æˆ‘ä»¬çš„çº¦å®šğŸ‘
    status: 0
    img:
  - desc: å¸¦ä¸Šä½ æˆ‘çš„å®¶äººå»èšä¼šã€æ—…æ¸¸ğŸš™
    status: 0
    img:
  - desc: æ¥ä¸€åœºéš¾å¿˜çš„æ±‚å©šğŸğŸ’
    status: 0
    img:
  - desc: åœ¨æœ‹å‹é¢å‰å¤§æ–¹ä»‹ç»å½¼æ­¤ğŸ’‹
    status: 0
    img:
  - desc: æ‹å±äºæˆ‘ä»¬è‡ªå·±çš„å©šçº±ç…§ğŸ
    status: 0
    img:
  - desc: äº’ç›¸åœ¨æœ‹å‹åœˆæ™’ç»“å©šè¯ğŸ“‡
    status: 0
    img:
  - desc: è®¾è®¡ä¸€åœºæ¢¦ä¸­çš„å©šç¤¼ğŸ’¤ğŸŒ¹ğŸ‰
    status: 0
    img:
  - desc: æ‹¥æœ‰ä¸€ä¸ªçˆ±çš„ç»“æ™¶ï¼Œç»™äºˆå®è´æœ€å¥½çš„çˆ±ğŸ‘¶ğŸ‘¼
    status: 0
    img:
  - desc: ä½™ç”Ÿæ¼«æ¼«ï¼Œæ‰§å­ä¹‹æ‰‹ï¼Œä¸å­å•è€ğŸ’
    status: 0
    img: